plan_trip:
  description: 'Create a list of must-visit places for today for a tourist in {location}. The list should be in an optimal order based on their location. The final answer must be a structured JSON object with a list of Russian location names.'
  expected_output: 'A JSON object with a single key "locations" which contains a list of strings representing the Russian names of the places/attractions.'
